config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'zips#index'
  resources :zips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# class ApplicationRecord < ActiveRecord::Base
#   self.abstract_class = true
# end

app/models/zip.rb
# frozen_string_literal: true

class Zip
  # include ActiveModel::Model
  include Mongoid::Document
  include Mongoid::Timestamps
  field :id, type: String
  field :city, type: String
  field :state, type: String
  field :population, type: Integer

  # attr_accessor :id, :city, :state, :population

  # def to_s
  #   "#{@id}: #{@city}, #{@state}, pop=#{@population}"
  # end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :configure_permitted_parameters, if: :device_controller?
  helper_method :current_time

  def current_time
    current_time = DateTime.now
  end
  # OPTIMIZE: make current_time method give time in EST

  # def configure_permitted_parameters
  #   device_parameter_sanitizer.permit(:sign_up, keys: [:username])
  #   device_parameter_sanitizer.permit(:account_update, keys: [:username])
  # end
end

app/controllers/zips_controller.rb
# frozen_string_literal: true

class ZipsController < ApplicationController
  before_action :set_zip, only: %i[show edit update destroy]
  # before_action :authenticate_user!, except: [:index, :show]

  # GET /zips
  # GET /zips.json
  def index
    # @zips = Zip.all
    # sleep 2
    # args = params.clone
    # args[:sort] = get_sort_hash(args[:sort])
    # @zips = Zip.paginate(args)
    @zips = if params[:search].blank?
              Zip.all.order(state: :desc).paginate(page: params[:page], per_page: 10)
            else
              Zip.search(params[:search]).paginate(page: params[:page], per_page: 10)
            end
  end

  # GET /zips/1
  # GET /zips/1.json
  def show; end

  # GET /zips/new
  def new
    @zip = Zip.new
  end

  # GET /zips/1/edit
  def edit; end

  # POST /zips
  # POST /zips.json
  def create
    @zip = Zip.new(zip_params)

    respond_to do |format|
      if @zip.save
        format.html { redirect_to @zip, notice: 'Zip was successfully created.' }
        format.json { render :show, status: :created, location: @zip }
      else
        format.html { render :new }
        format.json { render json: @zip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zips/1
  # PATCH/PUT /zips/1.json
  def update
    respond_to do |format|
      if @zip.update(zip_params)
        format.html { redirect_to @zip, notice: 'Zip was successfully updated.' }
        format.json { render :show, status: :ok, location: @zip }
      else
        format.html { render :edit }
        format.json { render json: @zip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zips/1
  # DELETE /zips/1.json
  def destroy
    @zip.destroy
    respond_to do |format|
      format.html { redirect_to zips_url, notice: 'Zip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_zip
    @zip = Zip.find(params[:id])
  end

  # Never trust parameters from the scary Internet, only allow the white list through.
  def zip_params
    params.require(:zip).permit(:id, :city, :state, :population, :search)
  end

  # create a hash sort spec from query parameters
  # sort = state: 1, city, population: -1
  # {state: 1, city: 1, population: -1}
  # def get_sort_hash(sort)
  #   order = {}
  #   return order if sort.nil?

  #   sort.split(',').each do |term|
  #     args = term.split(':')
  #     dir = args.size < 2 || args[1].to_i >= 0 ? 1 : -1
  #     order[args[0]] = dir
  #   end
  #   order
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # FIXME: nothing works
  def active_class(controller_name, action_name)
    # 'active' if current_page?(controller: controller_name, action: action_name)
  end

  def active_span(controller_name, action_name)
    # '(current)' if current_page?(controller: controller_name, action: action_name)
  end
end

app/helpers/zips_helper.rb
# frozen_string_literal: true

module ZipsHelper
  def to_zip(value)
    # change value to a Zip if not already a Zip
    value.is_a?(Zip) ? value : Zip.new(value)
  end
end

app/views/layouts/_footer.html.erb
<div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
        </div>
        <div class="three wide column">
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">Zips app.</h4>
          <h4 class="ui blue header">JuPlutonic © <%=current_time.strftime('%Y')%>.</h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="ui fixed inverted menu" id="navbar">
  <div class="ui container">
    <a href="/" class="header item">
    <%= semantic_icon('mail outline') %>
      Zips
    </a>

    <div class="item <%= active_class('zips', 'city') %>">
    <%#= semantic_icon('edit') %>
    <%=link_to '/zips', class: "nav-link" do %>
       <strong>🏙</strong> Cities
       <span class="sr-only"> <%= active_span('zips', 'city') %> </span>
    <% end %>
    </div>

    <div class="item <%= active_class('zips', 'state') %>">
    <%#= semantic_icon('mail') %>
    <%= link_to '/zips/state', class: "nav-link" do %>
      <strong>🗽</strong>  States
      <span class="sr-only"> <%= active_span('zips', 'state') %> </span>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zips</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %><!--, 'data-turbolinks-track': 'reload' %>-->
    <%= javascript_include_tag 'application' %> <!--, 'data-turbolinks-track': 'reload' %>-->
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="ui container" id="app-wrapper">
    <%= semantic_flash %>
    <%# TODO: Add vendor/, Gulp(PostCSS) pipeline to Rails%>
    <%# TODO: Add font-mfizz.css pages.scss to Rails%>
    <%= yield %>
    </div>
    <%=render 'layouts/footer' %>
  </body>
</html>

app/views/zips/_form.html.erb
<%= form_with(model: zip, local: true) do |form| %>
  <% if zip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zip.errors.count, "error") %> prohibited this zip from being saved:</h2>

      <ul>
      <% zip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="ui form">
    <div class="field">
      <%= form.label :id %>
      <%= form.text_field :id %>
    </div>

    <div class="field">
      <%= form.label :city %>
      <%= form.text_field :city %>
    </div>

    <div class="field">
      <%= form.label :state %>
      <%= form.text_field :state %>
    </div>

    <div class="field">
      <%= form.label :population %>
      <%= form.number_field :population %>
    </div>
    <div class="actions">
      <%#= form.submit %>
      <%= button_tag "Submit", class: 'ui primary button', data: { disable_with: "<i class='fa fa-spinner fa-spin fa-fw'></i> Saving…"} %>
    </div>
  </div>
<% end %>

app/views/zips/edit.html.erb
<h1>Editing Zip</h1>

<%= render 'form', zip: @zip %>

<br>
<div class="ui celled">
<%= link_to 'Show', @zip, class: 'ui button left' %>
<%= link_to 'Back', zips_path, class: 'ui button right' %>
</div>
<br>

app/views/zips/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<br>
<br>
<br>
<!-- SEARCH BAR -->
<div class="ui secondary menu">
  <div class="right menu"
    <div class="item">
      <%= form_tag zips_path, method: :get do %>
      <div class="ui action left icon input">
        <i class="search icon"></i>
        <%= text_field_tag :search, params[:search], placeholder: 'Search…'%>
        <%= button_tag "Search", name: nil, class: 'ui teal button', data: { disable_with: " <i class='fa fa-spinner fa-spin fa-fw'></i> Searching… " } %>
      </div>
      <%end%>
      <% # FIXME: Search results always empty. %>
    </div>
  </div>
</div>

<h1>Zips</h1>

<!-- TABLE -->
<table class="ui fixed single line sortable celled table">
  <thead>
    <tr>
      <th>Id</th>
      <th>City</th>
      <th>State <%=semantic_icon('sort')%></th> <!--th class="descending" -->
      <th colspan="4">Population</th>
    </tr>
  </thead>

  <tbody>
    <% @zips.each do |zip| %>
      <% zip = to_zip(zip) %>
      <tr>
        <td><%= zip.id %></td>
        <td><%= zip.city %></td>
        <td><%= zip.state %></td> <!-- post.user.username" -->
        <td><%= zip.population %></td> <!--<td><#%= time_ago_in_words(post.created_at)"%> ago</td>-->
        <td class="positive"><%= link_to 'Show', zip %></td>
        <td class="warnings"><%= link_to 'Edit', edit_zip_path(zip) %></td>
        <td class="negative"><%= link_to '♻ Delete', zip, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td> <!-- <i class="trash outline icon"></i></td> --> <!--semantic_icon('trash outline') + 'Delete' -->
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th>
        <strong>Total: <%=@zips.count%></strong>
      </th>
      <th></th>
      <th></th>

      <th></th>
      <th colspan="2"></th>
    </tr>
  </tfoot>
</table>

<br>

<%= link_to 'New Zip', new_zip_path, class: 'ui primary button'%>

<br>
<div class="ui segment" id="paginate">
<%= will_paginate @zips, renderer: WillPaginateSemanticUi::ActionView::Renderer %>
</div>

<script>
  $('table').tablesort()
</script>

app/views/zips/new.html.erb
<h1>New Zip</h1>
<div class="ui teal segment">
<%= render 'form', zip: @zip %>
</div>
<br>

<%= link_to 'Back', zips_path, class: 'ui basic secondary button' %>

app/views/zips/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<br>
<br>
<div class="ui secondary menu">
  <div class="item">
  <%= link_to 'Back to Zips', zips_path, class: 'ui button' %>
  </div>
</div>
<div class="ui divided selection list">
<a class="item">
 <div class="ui teal horizontal label">Id:</div>
  <%= @zip.id%>
</a>
<a class="item">
<div class="ui orange horizontal label">City:</div>
  <%= @zip.city%>
</a>
<a class="item">
<div class="ui purple horizontal label">State:</div>
  <%= @zip.state%>
</a>
<a class="item">
<div class="ui blue horizontal label">Population:</div>
  <%= @zip.population%>
</a>
<div class="ui secondary menu">
  <div class="item">
  <%= link_to 'Edit', edit_zip_path(@zip), class: 'ui button' %>
  </div>
</div>